services:
  puppyping:
    build:
      context: .#https://github.com/badbayesian/puppy_ping.git
      dockerfile: Dockerfile
    container_name: puppyping
    environment:
      TZ: America/Chicago
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      EMAIL_FROM: ${EMAIL_FROM}
      EMAILS_TO: ${EMAILS_TO}
    volumes:
      - /mnt/thebutler/config/puppy_ping/cache:/app/.cache
    restart: no
  postgres:
    image: postgres:18
    container_name: puppyping-postgres
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      TZ: America/Chicago
    volumes:
      - /mnt/thebutler/config/puppy_ping/data/postgres:/var/lib/postgresql
    ports:
      - 5433:5432
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: puppyping-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
      PGADMIN_REPLACE_SERVERS_ON_STARTUP: "True"
    ports:
      - 5050:80
    volumes:
      - /mnt/thebutler/config/puppy_ping/data/pgadmin:/var/lib/pgadmin
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json:ro
    depends_on:
      - postgres
networks: {}
